export const siteConfig = {
  name: 'SOHO Cambados',
  legalDisplayName: 'SOHO Cambados',
  address: 'Calle A Mariña, 3, 36630 Cambados, Pontevedra',
  shortAddress: 'A Mariña 3, Cambados',
  phoneDisplay: '+34 644 53 57 78',
  phoneHref: '+34644535778',
  whatsappDisplay: '+34 635 47 62 21',
  whatsappHref: '34635476221',
  email: 'cambadossoho@gmail.com',
  mapsUrl: 'https://share.google/WsSNi8rh0i58zLk2p',
  instagramUrl: 'https://www.instagram.com/sohocambados?igsh=MWNmdmNmM3dodWExMg==',
  facebookUrl: 'https://www.facebook.com/share/1CVBvEATjU/?mibextid=wwXIfr',
  cayluUrl: 'https://appcaylu.caylu.es/restaurantes/75',
  menuSourceUrl: 'https://menuyvinos.com/soho/',
  logoPath: '/soho-logo-green.png',
  compactLogoPath: '/soho-logo.png',
} as const;
